#!/usr/bin/env bash
# configure Nginx server to listen port 80

#remove default
rm /etc/nginx/sites-enabled/default
#configure for pport 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
