#!/usr/bin/env bash
# Bash script that configures an Ubuntu server to resolve localhost 127.0.0.2 and facebook 8.8.8.8
cp /etc/hosts ~/temp
sed -i s/127.0.0.1/127.0.0.2/ ~/temp
echo "8.8.8.8 facebook.com" >> ~/temp
cp -f ~/temp /etc/hosts
